-- Name: activity_type; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.activity_type AS ENUM (
    'Activity',
    'Yoga_class'
);


ALTER TYPE public.activity_type OWNER TO postgres;

--
-- Name: level_type; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.level_type AS ENUM (
    'Beginner',
    'Advanced',
    'Expertise'
);


ALTER TYPE public.level_type OWNER TO postgres;

--
-- Name: teacher; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teacher (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    surname character varying(50) NOT NULL,
    role character varying(50) NOT NULL,
    main_expertise character varying(100) NOT NULL,
    about character varying(250) NOT NULL,
    image text
);


ALTER TABLE public.teacher OWNER TO postgres;

--
-- Name: activity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activity (
    id integer NOT NULL,
    title character varying(50) NOT NULL,
    level public.level_type,
    short_description character varying(100) NOT NULL,
    about character varying(500) NOT NULL,
    ideal_for character varying(250) NOT NULL,
    main_benefit character varying(250) NOT NULL,
    additional_info character varying(250),
    roomid integer,
    schedule text NOT NULL,
    image text,
    type public.activity_type DEFAULT 'Activity'::public.activity_type
);


ALTER TABLE public.activity OWNER TO postgres;

--
-- Name: activity_base; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activity_base (
    id integer NOT NULL,
    roomid integer,
    schedule text,
    image text,
    type text,
    teacher_id integer DEFAULT 1 NOT NULL
);


ALTER TABLE public.activity_base OWNER TO postgres;

--
-- Name: activity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.activity_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.activity_id_seq OWNER TO postgres;

--
-- Name: activity_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.activity_id_seq OWNED BY public.activity.id;


--
-- Name: activity_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.activity_id_seq1
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.activity_id_seq1 OWNER TO postgres;

--
-- Name: activity_id_seq1; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.activity_id_seq1 OWNED BY public.activity_base.id;


--
-- Name: activity_translations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activity_translations (
    id integer NOT NULL,
    activity_id integer,
    language_code character varying(5),
    title text,
    level text,
    short_description text,
    about text,
    ideal_for text,
    main_benefit text,
    additional_info text,
    schedule text
);


ALTER TABLE public.activity_translations OWNER TO postgres;

--
-- Name: activity_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.activity_translations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.activity_translations_id_seq OWNER TO postgres;

--
-- Name: activity_translations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.activity_translations_id_seq OWNED BY public.activity_translations.id;


--
-- Name: areas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.areas (
    id bigint NOT NULL,
    title character varying NOT NULL,
    image text
);


ALTER TABLE public.areas OWNER TO postgres;

--
-- Name: areas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.areas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.areas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messaggi; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messaggi (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    testo text
);


ALTER TABLE public.messaggi OWNER TO postgres;

--
-- Name: participant; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.participant (
    id integer NOT NULL,
    name character varying(50),
    image text
);


ALTER TABLE public.participant OWNER TO postgres;

--
-- Name: partecipant_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.partecipant_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.partecipant_id_seq OWNER TO postgres;

--
-- Name: partecipant_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.partecipant_id_seq OWNED BY public.participant.id;


--
-- Name: review_translations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.review_translations (
    id integer NOT NULL,
    review_id integer NOT NULL,
    language_code character varying(5) NOT NULL,
    review text NOT NULL
);


ALTER TABLE public.review_translations OWNER TO postgres;

--
-- Name: review_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.review_translations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.review_translations_id_seq OWNER TO postgres;

--
-- Name: review_translations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.review_translations_id_seq OWNED BY public.review_translations.id;


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews (
    iduser integer NOT NULL,
    idactivity integer NOT NULL,
    stars integer,
    review text,
    date date,
    CONSTRAINT reviews_stars_check CHECK (((stars >= 1) AND (stars <= 5)))
);


ALTER TABLE public.reviews OWNER TO postgres;

--
-- Name: reviews_base; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews_base (
    id integer NOT NULL,
    idparticipant integer NOT NULL,
    idactivity integer NOT NULL,
    stars integer NOT NULL,
    date date NOT NULL,
    CONSTRAINT reviews_stars_check1 CHECK (((stars >= 1) AND (stars <= 5)))
);


ALTER TABLE public.reviews_base OWNER TO postgres;

--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.reviews_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.reviews_id_seq OWNER TO postgres;

--
-- Name: reviews_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.reviews_id_seq OWNED BY public.reviews_base.id;


--
-- Name: room; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.room (
    id integer NOT NULL,
    title character varying(30),
    description character varying(450) NOT NULL,
    image text,
    features text
);


ALTER TABLE public.room OWNER TO postgres;

--
-- Name: room_base; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.room_base (
    id integer NOT NULL,
    image text NOT NULL
);


ALTER TABLE public.room_base OWNER TO postgres;

--
-- Name: room_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.room_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.room_id_seq OWNER TO postgres;

--
-- Name: room_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.room_id_seq OWNED BY public.room.id;


--
-- Name: room_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.room_id_seq1
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.room_id_seq1 OWNER TO postgres;

--
-- Name: room_id_seq1; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.room_id_seq1 OWNED BY public.room_base.id;


--
-- Name: room_translations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.room_translations (
    id integer NOT NULL,
    room_id integer NOT NULL,
    language_code character varying(5) NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    features text
);


ALTER TABLE public.room_translations OWNER TO postgres;

--
-- Name: room_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.room_translations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.room_translations_id_seq OWNER TO postgres;

--
-- Name: room_translations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.room_translations_id_seq OWNED BY public.room_translations.id;


--
-- Name: teacher_base; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teacher_base (
    id integer NOT NULL,
    image text NOT NULL,
    "Name" text,
    "Surname" text
);


ALTER TABLE public.teacher_base OWNER TO postgres;

--
-- Name: teacher_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.teacher_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.teacher_id_seq OWNER TO postgres;

--
-- Name: teacher_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.teacher_id_seq OWNED BY public.teacher.id;


--
-- Name: teacher_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.teacher_id_seq1
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.teacher_id_seq1 OWNER TO postgres;

--
-- Name: teacher_id_seq1; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.teacher_id_seq1 OWNED BY public.teacher_base.id;


--
-- Name: teacher_translations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teacher_translations (
    "NON_USARE" integer NOT NULL,
    id integer NOT NULL,
    language_code character varying(5) NOT NULL,
    role text NOT NULL,
    main_expertise text NOT NULL,
    about text NOT NULL
);


ALTER TABLE public.teacher_translations OWNER TO postgres;

--
-- Name: COLUMN teacher_translations."NON_USARE"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.teacher_translations."NON_USARE" IS 'non mi fa eliminare la colonna, lasciamola così e non usiamola';


--
-- Name: teacher_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.teacher_translations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.teacher_translations_id_seq OWNER TO postgres;

--
-- Name: teacher_translations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.teacher_translations_id_seq OWNED BY public.teacher_translations."NON_USARE";


--
-- Name: teaches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teaches (
    idteacher integer NOT NULL,
    idactivity integer NOT NULL
);


ALTER TABLE public.teaches OWNER TO postgres;

--
-- Name: activity id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activity ALTER COLUMN id SET DEFAULT nextval('public.activity_id_seq'::regclass);


--
-- Name: activity_base id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activity_base ALTER COLUMN id SET DEFAULT nextval('public.activity_id_seq1'::regclass);


--
-- Name: activity_translations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activity_translations ALTER COLUMN id SET DEFAULT nextval('public.activity_translations_id_seq'::regclass);


--
-- Name: participant id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.participant ALTER COLUMN id SET DEFAULT nextval('public.partecipant_id_seq'::regclass);


--
-- Name: review_translations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review_translations ALTER COLUMN id SET DEFAULT nextval('public.review_translations_id_seq'::regclass);


--
-- Name: reviews_base id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews_base ALTER COLUMN id SET DEFAULT nextval('public.reviews_id_seq'::regclass);


--
-- Name: room id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.room ALTER COLUMN id SET DEFAULT nextval('public.room_id_seq'::regclass);


--
-- Name: room_base id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.room_base ALTER COLUMN id SET DEFAULT nextval('public.room_id_seq1'::regclass);


--
-- Name: room_translations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.room_translations ALTER COLUMN id SET DEFAULT nextval('public.room_translations_id_seq'::regclass);


--
-- Name: teacher id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher ALTER COLUMN id SET DEFAULT nextval('public.teacher_id_seq'::regclass);


--
-- Name: teacher_base id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher_base ALTER COLUMN id SET DEFAULT nextval('public.teacher_id_seq1'::regclass);


--
-- Name: activity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.activity_id_seq', 30, true);


--
-- Name: activity_id_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.activity_id_seq1', 1, false);


--
-- Name: activity_translations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.activity_translations_id_seq', 51, true);


--
-- Name: areas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.areas_id_seq', 1, false);


--
-- Name: partecipant_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.partecipant_id_seq', 1, false);


--
-- Name: review_translations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.review_translations_id_seq', 30, true);


--
-- Name: reviews_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reviews_id_seq', 1, false);


--
-- Name: room_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.room_id_seq', 38, true);


--
-- Name: room_id_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.room_id_seq1', 1, false);


--
-- Name: room_translations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.room_translations_id_seq', 30, true);


--
-- Name: teacher_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.teacher_id_seq', 35, true);


--
-- Name: teacher_id_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.teacher_id_seq1', 1, false);


--
-- Name: teacher_translations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.teacher_translations_id_seq', 26, true);


--
